Author: T. Majidzadeh

Date Created: December 10, 2024

Date Updated: December 10, 2024

Notes: T. Majidzadeh added author credit, description, and relative filepath April 30, 2025 for GitHub publication.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import statsmodels.stats as sm_stats
from scipy.stats import chi2_contingency
import seaborn as sns
import os
import math

C:\ProgramData\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
path = '../Civil Affairs Network - FINAL_December 7, 2024_14.00_v2.xlsx'
raw_data = pd.read_excel(path, sheet_name="Raw", header=[0, 1])

In [3]:
raw_data[('Q1.5_0')].columns

Index(['How much do you agree with this statement from 0-100? 0 being the lowest and 100 being the highest. Slide to enter a value.\n\n\n\n\n"Undocumented workers are often exploited in the U.S., despite being a crucial part of the nation’s economy. To protect their rights and drive economic growth, we should take immediate steps to significantly expand the availability of work visas." - Level of Agreement'], dtype='object')

In [4]:
began_treatment = [
    not math.isnan(x) for x in raw_data[
    ('NQ4.1_First Click', 'Timing - First Click')
    ]
]

began_control = [
    not math.isnan(x) for x in raw_data[
    ('NQ3.1_First Click', 'Timing - First Click')
    ]
]

began_survey = pd.concat([raw_data[began_treatment], raw_data[began_control]])

In [5]:
raw_data[began_control]

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,NQ4.9_Click Count,Q2.4_1,NQ4.11_First Click,NQ4.11_Last Click,NQ4.11_Page Submit,NQ4.11_Click Count,Q2.5_11,transaction_id,Control,Treatment
,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,Timing - Click Count,How much do you agree with this statement from 0-100? 0 being the lowest and 100 being the highest. Slide to enter a value. - Level of Agreement,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,How much do you agree with this statement from 0-100? 0 being the lowest and 100 being the highest. Slide to enter a value. - Level of Agreement,transaction_id,Control,Treatment
0,2024-12-06 12:36:54,2024-12-06 12:38:10,IP Address,172.56.70.103,100,75,True,2024-12-06 12:38:11.352,R_1iPQOVMwHTh3kbQ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6mFiGCmrgdo49JhWi0rTfh,True,False
1,2024-12-06 12:37:06,2024-12-06 12:38:14,IP Address,47.159.143.250,100,68,True,2024-12-06 12:38:15.508,R_3rOYQJ2oAekAzNa,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6d4bLN1fEsHRvj5riTUQG1,True,False
2,2024-12-06 12:37:14,2024-12-06 12:38:28,IP Address,172.59.136.93,100,73,True,2024-12-06 12:38:28.591,R_5KHoSb8sMKNBb7p,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69Gr7w21tq1aPXvuIZF8Ej,True,False
7,2024-12-06 12:37:32,2024-12-06 12:38:53,IP Address,172.59.194.206,100,80,True,2024-12-06 12:38:54.249,R_7WNoeuNB4wYPkYY,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7av5fVUhVj93Npzfs26AqM,True,False
8,2024-12-06 12:37:27,2024-12-06 12:38:58,IP Address,172.74.214.55,100,91,True,2024-12-06 12:38:58.697,R_6HxQxzJGMAMxJTj,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1ZkZAsB5vw9ChFRDYbVB8v,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,2024-12-06 17:07:51,2024-12-06 17:13:05,IP Address,99.154.7.135,100,313,True,2024-12-06 17:13:05.704,R_1wu9Y3lM7Nddieo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0LDrCzevvglJ0P2vJjF9nL,True,False
315,2024-12-06 17:16:15,2024-12-06 17:18:57,IP Address,73.52.101.101,100,161,True,2024-12-06 17:18:57.863,R_73MtG3bz8VRgSLD,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4yh5baSWS17UCjA6QMeICq,True,False
358,2024-12-06 18:37:53,2024-12-06 18:40:26,IP Address,70.124.97.161,100,153,True,2024-12-06 18:40:27.074,R_7MMzIY6eiDVB5D4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0gjXdXsE6lLaW5MavbasrH,True,False
362,2024-12-06 18:51:31,2024-12-06 18:53:31,IP Address,107.139.134.188,100,119,True,2024-12-06 18:53:31.591,R_7LJLgpaZUP7AxLX,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6B7DkUuUqfrR0JTeWuGi1B,True,False
365,2024-12-06 19:12:25,2024-12-06 19:14:49,IP Address,24.176.250.49,100,143,True,2024-12-06 19:14:49.918,R_6PsI7BZbHm7gYSt,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06HZ9nJqmXKTKfkxx7Iunx,True,False

In [6]:
began_survey['Completed Treatment'] = [
    (not math.isnan(x)) * 1 for x in began_survey[
    ('Q2.5_11', 'How much do you agree with this statement from 0-100? 0 being the lowest and 100 being the highest. Slide to enter a value. - Level of Agreement')
    ]
]

began_survey['Completed Control'] = [
    (not math.isnan(x)) * 1 for x in began_survey[
    ('Q1.5_0', 'How much do you agree with this statement from 0-100? 0 being the lowest and 100 being the highest. Slide to enter a value.\n\n\n\n\n"Undocumented workers are often exploited in the U.S., despite being a crucial part of the nation’s economy. To protect their rights and drive economic growth, we should take immediate steps to significantly expand the availability of work visas." - Level of Agreement')
    ]
]

In [7]:
began_survey['Treatment']

    Treatment
3        True
4        True
5        True
6        True
13       True
..        ...
271     False
315     False
358     False
362     False
365     False

[226 rows x 1 columns]

In [8]:
began_survey['TreatAssign'] = [x * 1 for x in began_survey[('Treatment', 'Treatment')]]
began_survey['Attrition'] = 1- (began_survey['Completed Treatment'] + began_survey['Completed Control'])

In [9]:
began_survey[began_survey['Attrition'] == 1][['Q1.1_11', 'Q2.1_11', 'Treatment']]

,Q1.1_11,Q2.1_11,Treatment
,"How much do you agree with this statement from 0-100? 0 being the lowest and 100 being the highest. Slide to enter a value.\n\n\n\n""Despite immigrants' deep ties to their communities, it’s disgraceful that many lack the right to vote, relegating them to second-class citizens without proper representation."" - Level of Agreement",How much do you agree with this statement from 0-100? 0 being the lowest and 100 being the highest. Slide to enter a value. - Level of Agreement,Treatment
116,NaN,70.0,True
118,NaN,16.0,True
127,NaN,81.0,True
170,NaN,0.0,True
172,NaN,NaN,True
173,NaN,26.0,True
177,NaN,100.0,True
178,NaN,1.0,True
180,NaN,NaN,True
181,NaN,25.0,True
182,NaN,82.0,True
183,NaN,72.0,True
185,NaN,NaN,True
201,NaN,NaN,True
223,NaN,0.0,True
243,NaN,NaN,True
244,NaN,NaN,True
246,NaN,100.0,True
309,NaN,0.0,True
321,NaN,80.0,True
35,39.0,NaN,False
166,70.0,NaN,False
174,NaN,NaN,False
192,35.0,NaN,False
198,NaN,NaN,False
232,65.0,NaN,False

In [10]:
began_survey = began_survey[['NQ2.4','NQ2.5', 'NQ2.6','NQ2.7','NQ2.8','NQ2.9', 'Q1.1_11', 'Q2.1_11', 'TreatAssign', 'Completed Treatment', 'Completed Control', 'Attrition']]

In [27]:
treatment_map = {'NQ2.4':'party','NQ2.5':'leaning','NQ2.6':'gender','NQ2.7':'age',
                 'NQ2.8':'race','NQ2.9':'hispanic','NQ2.10':'citizenship', 'Q1.1_11': 'Q1_Con',
                 'Q2.1_11':'Q1_Treat','Q2.2_11':'Q2','Q2.3_11':'Q3','Q2.4_1':'Q4',
                 'Q2.5_11':'Q5'}
began_survey.rename(columns=treatment_map, inplace=True)
q1_treat_name = began_survey['Q1_Treat'].columns[0]
q1_con_name = began_survey['Q1_Con'].columns[0]
began_survey['Q1_Comb'] = began_survey['Q1_Treat'].fillna(0)[q1_treat_name] + began_survey['Q1_Con'].fillna(0)[q1_con_name]

In [28]:
began_survey.columns = began_survey.columns.droplevel(1)

In [30]:
began_survey

,party,leaning,gender,age,race,hispanic,Q1_Con,Q1_Treat,TreatAssign,Completed Treatment,Completed Control,Attrition,Q1_Comb
3,Republican,Strongly Conservative,man,35-44,White,No,NaN,73.0,1,1,0,0,73.0
4,Democrat,Liberal,woman,55-64,White,No,NaN,100.0,1,1,0,0,100.0
5,Republican,Moderate,woman,35-44,White,No,NaN,60.0,1,1,0,0,60.0
6,Democrat,Lean Liberal,woman,55-64,White,No,NaN,82.0,1,1,0,0,82.0
13,Democrat,Liberal,man,65 or older,Black or African American,No,NaN,54.0,1,1,0,0,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,Republican,Moderate,man,25-34,Two or more,Yes,55.0,NaN,0,0,1,0,55.0
315,Democrat,Liberal,man,25-34,Other race,Yes,75.0,NaN,0,0,1,0,75.0
358,Democrat,Moderate,man,18-24,White,Yes,100.0,NaN,0,0,1,0,100.0
362,Democrat,Strongly Liberal,man,18-24,Other race,Yes,92.0,NaN,0,0,1,0,92.0
365,Democrat,Lean Liberal,woman,55-64,White,Yes,74.0,NaN,0,0,1,0,74.0

In [31]:
covariates = ['party','leaning','gender','age','race','hispanic']

In [32]:
# From I. Vaimberg
# turn covariates into one hot encoded columns
df_dummy = pd.get_dummies(began_survey[covariates])

one_hot_covariates = [#'party_Democrat',
 'party_Independent', 'party_Other',
'party_Republican',

'leaning_Conservative', 'leaning_Lean Conservative',
'leaning_Lean Liberal', 'leaning_Liberal', 'leaning_Moderate',
'leaning_Strongly Conservative',
 #'leaning_Strongly Liberal',

#'gender_man',
 'gender_woman',

#'age_18-24',
'age_25-34', 'age_35-44',
'age_45-54', 'age_55-64', 'age_65 or older',

'race_American Indian or Alaska Native', 'race_Asian',
'race_Black or African American',
'race_Native Hawaiian or Other Pacific Islander', 'race_Other race',
'race_Two or more',
#'race_White',

#'hispanic_No',
 'hispanic_Yes',
]


began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]

In [33]:
new_covariates = [#'party_Democrat',
 'party_Independent', 'party_Other',
'party_Republican',

'leaning_Conservative', 'leaning_Lean Conservative',
'leaning_Lean Liberal', 'leaning_Liberal', 'leaning_Moderate',
'leaning_Strongly Conservative',
 #'leaning_Strongly Liberal',

#'gender_man',
 'gender_woman',

#'age_18-24',
'age_25-34', 'age_35-44',
'age_45-54', 'age_55-64', 'age_65 or older',

'race_American Indian or Alaska Native', 'race_Asian',
'race_Black or African American',
'race_Native Hawaiian or Other Pacific Islander', 'race_Other race',
'race_Two or more',
#'race_White',

#'hispanic_No',
 'hispanic_Yes'
]

In [34]:
rs = began_survey


X = rs[['TreatAssign']+one_hot_covariates]#+interaction_cols]
y = rs['Attrition']


X = sm.add_constant(X)
attrition_model = sm.OLS(y,X.astype(float))
attrition_results = attrition_model.fit(cov_type='HC3')
print(attrition_results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              Attrition   R-squared:                       0.087
Model:                            OLS   Adj. R-squared:                 -0.017
Method:                 Least Squares   F-statistic:                    0.7732
Date:                Sun, 15 Dec 2024   Prob (F-statistic):              0.762
Time:                        10:21:21   Log-Likelihood:                -52.225
No. Observations:                 226   AIC:                             152.5
Df Residuals:                     202   BIC:                             234.5
Df Model:                          23
Covariance Type:                  HC3
==================================================================================================================
                                                     coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------------
const                                             -0.0312      0.098     -0.320      0.749      -0.222       0.160
TreatAssign                                        0.1160      0.047      2.490      0.013       0.025       0.207
party_Independent                                 -0.0521      0.056     -0.935      0.350      -0.161       0.057
party_Other                                       -0.2860      0.227     -1.258      0.208      -0.731       0.159
party_Republican                                  -0.0159      0.065     -0.244      0.807      -0.144       0.112
leaning_Conservative                               0.0023      0.083      0.028      0.978      -0.161       0.166
leaning_Lean Conservative                          0.1772      0.118      1.508      0.132      -0.053       0.408
leaning_Lean Liberal                               0.1262      0.115      1.097      0.273      -0.099       0.352
leaning_Liberal                                    0.0655      0.073      0.898      0.369      -0.078       0.209
leaning_Moderate                                   0.0845      0.054      1.561      0.119      -0.022       0.190
leaning_Strongly Conservative                      0.0610      0.091      0.667      0.505      -0.118       0.240
gender_woman                                       0.0266      0.048      0.551      0.582      -0.068       0.121
age_25-34                                         -0.0460      0.077     -0.595      0.552      -0.198       0.106
age_35-44                                         -0.0413      0.089     -0.464      0.643      -0.216       0.133
age_45-54                                          0.0688      0.091      0.754      0.451      -0.110       0.248
age_55-64                                          0.0835      0.099      0.842      0.400      -0.111       0.278
age_65 or older                                    0.0531      0.109      0.488      0.626      -0.160       0.266
race_American Indian or Alaska Native              0.1042      0.206      0.507      0.612      -0.299       0.507
race_Asian                                        -0.0522      0.088     -0.597      0.551      -0.224       0.119
race_Black or African American                     0.0067      0.068      0.098      0.922      -0.126       0.140
race_Native Hawaiian or Other Pacific Islander    -0.1968      0.152     -1.298      0.194      -0.494       0.100
race_Other race                                    0.0471      0.134      0.351      0.725      -0.215       0.310
race_Two or more                                   0.1034      0.145      0.715      0.475      -0.180       0.387
hispanic_Yes                                      -0.0266      0.083     -0.319      0.750      -0.190       0.137
==============================================================================
Omnibus:                       97.802   Durbin-Watson:                   1.118
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              247.008
Skew:                           2.069   Prob(JB):                     2.31e-54
Kurtosis:                       6.019   Cond. No.                         23.6
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [35]:
x1, x2 = began_survey[began_survey['TreatAssign'] == 1]['Attrition'], began_survey[began_survey['TreatAssign'] == 0]['Attrition']
sm_stats.weightstats.ttest_ind(x1, x2, alternative='two-sided', usevar='pooled', weights=(None, None), value=0)

(2.615403226968271, 0.009517820730405208, 224.0)

In [36]:
began_survey \
    .rename(columns={"leaning":"Count","TreatAssign":"Treatment"}) \
    .groupby(['Attrition','Treatment']) \
    .count()[['Count']]

                     Count
Attrition Treatment
0         0            100
          1            100
1         0              6
          1             20

In [37]:
began_survey[['Q1_Con', 'Q1_Treat', 'Q1_Comb']]

     Q1_Con  Q1_Treat  Q1_Comb
3       NaN      73.0     73.0
4       NaN     100.0    100.0
5       NaN      60.0     60.0
6       NaN      82.0     82.0
13      NaN      54.0     54.0
..      ...       ...      ...
271    55.0       NaN     55.0
315    75.0       NaN     75.0
358   100.0       NaN    100.0
362    92.0       NaN     92.0
365    74.0       NaN     74.0

[226 rows x 3 columns]

In [51]:
rs = began_survey[[not math.isnan(x) for x in began_survey['Q1_Comb']]]

rs['Treat_Attrition'] = rs['Attrition'] * rs['TreatAssign']

X = rs[['Attrition', 'TreatAssign', 'Treat_Attrition']+one_hot_covariates]#+interaction_cols]
y = rs['Q1_Comb']


X = sm.add_constant(X)
attrition_treat_q1 = sm.OLS(y,X.astype(float))
attrition_treat_q1 = attrition_treat_q1.fit()
print(attrition_treat_q1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                Q1_Comb   R-squared:                       0.295
Model:                            OLS   Adj. R-squared:                  0.206
Method:                 Least Squares   F-statistic:                     3.341
Date:                Sun, 15 Dec 2024   Prob (F-statistic):           1.09e-06
Time:                        10:27:33   Log-Likelihood:                -1080.4
No. Observations:                 226   AIC:                             2213.
Df Residuals:                     200   BIC:                             2302.
Df Model:                          25
Covariance Type:            nonrobust
==================================================================================================================
                                                     coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------------
const                                             71.3908     10.055      7.100      0.000      51.563      91.218
Attrition                                        -20.8824     13.479     -1.549      0.123     -47.462       5.697
TreatAssign                                        4.8357      4.510      1.072      0.285      -4.058      13.729
Treat_Attrition                                    1.7640     15.544      0.113      0.910     -28.886      32.414
party_Independent                                -14.5985      6.056     -2.411      0.017     -26.539      -2.658
party_Other                                      -27.8517     32.197     -0.865      0.388     -91.341      35.637
party_Republican                                 -15.0609      6.713     -2.244      0.026     -28.298      -1.824
leaning_Conservative                             -35.8259      9.381     -3.819      0.000     -54.324     -17.328
leaning_Lean Conservative                        -32.6346     10.137     -3.219      0.001     -52.623     -12.646
leaning_Lean Liberal                             -15.0177      9.714     -1.546      0.124     -34.172       4.137
leaning_Liberal                                  -18.9003      7.913     -2.389      0.018     -34.504      -3.297
leaning_Moderate                                 -11.6906      7.208     -1.622      0.106     -25.903       2.522
leaning_Strongly Conservative                    -28.3995     10.016     -2.835      0.005     -48.150      -8.649
gender_woman                                      -3.1556      4.348     -0.726      0.469     -11.729       5.417
age_25-34                                         12.7425      8.129      1.567      0.119      -3.288      28.773
age_35-44                                          8.9456      8.517      1.050      0.295      -7.849      25.740
age_45-54                                         11.3391      8.161      1.389      0.166      -4.753      27.431
age_55-64                                          9.7600      8.363      1.167      0.245      -6.730      26.250
age_65 or older                                   -3.3000      8.589     -0.384      0.701     -20.237      13.637
race_American Indian or Alaska Native              4.4345     13.507      0.328      0.743     -22.200      31.069
race_Asian                                         3.5165      9.029      0.389      0.697     -14.288      21.321
race_Black or African American                     6.7114      7.019      0.956      0.340      -7.129      20.552
race_Native Hawaiian or Other Pacific Islander   -33.4819     31.557     -1.061      0.290     -95.709      28.745
race_Other race                                    3.8011     10.043      0.378      0.705     -16.002      23.605
race_Two or more                                   1.7082     12.261      0.139      0.889     -22.469      25.886
hispanic_Yes                                       6.1257      6.866      0.892      0.373      -7.414      19.665
==============================================================================
Omnibus:                        0.234   Durbin-Watson:                   2.021
Prob(Omnibus):                  0.890   Jarque-Bera (JB):                0.204
Skew:                           0.073   Prob(JB):                        0.903
Kurtosis:                       2.977   Cond. No.                         23.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.